spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5672
    username: qglfgzeu
    password: AXpPhAHHQbPkH_osc1-vqwVubqZjD8c2
    virtual-host: qglfgzeu
logging:
  level:
    org:
      hibernate:
        type: trace


